### ISSUE TITLE
Where are the settings for this in Wordpress Admin?

### ISSUE THREAD

**Issue by ScootRay** [bulgaru/sendy-hooks#2]
Greets,

I can't seem to find where the settings are for this plugin? Would you be so kind as to point me to the proper location? 

Thanks, looking forward to checking this out!
Ray

**Comment by bulgaru** [comment]
Hey, @ScootRay 

You should find them under the Settings menu section.
Here's a direct link: /wp-admin/options-general.php?page=sendy_hooks

**Comment by ScootRay** [comment]
Interesting, I when I go to that URL I get:

"Sorry, you are not allowed to access this page."

Let me know how I can help debug this.

Thanks!
Ray

--==> Follow me Along the Ray @ alongtheray.com... <==--

...a wandering alien from a different plane roaming the universe in a tiny camper...

**Comment by bulgaru** [comment]
Hey!

Can you see other options under the Setting menu?
Can you access those? What is your user role?

**Comment by ScootRay** [comment]
There’s no other options available, that’s why I posted here wondering where they were.

I’m at administrator role.

Lemme know what else I can do.

Thanks!
Ray

--==> Follow me Along the Ray @ alongtheray.com... <==--

...a wandering alien from a different plane roaming the universe in a tiny camper...

**Comment by bulgaru** [comment]
Did a clean-up of some of the legacy code used in the past. Please update with the new plugin version and please let me know if it solves the issue.

**Comment by ScootRay** [comment]
That did the trick! All good now I can play with it. ; )

Many thanks, Vladimir!
Ray
